### ISSUE TITLE
[solved] error

### ISSUE THREAD

**Issue by deikatsuo** [konkor/obmin#3]
![screenshot from 2017-07-27 04-03-57](https://user-images.githubusercontent.com/8337409/28643670-c9accfc4-7280-11e7-90ee-24bf276a9678.png)

**Comment by konkor** [comment]
TY fixed in the master.
Can you test after manual update from master branch...

### Install from GitHub branch (default master)
1. Download [install_obmin.sh](https://github.com/konkor/obmin/raw/master/install_obmin.sh)
```
wget https://github.com/konkor/obmin/raw/master/install_obmin.sh
chmod +x ./install_obmin.sh
```
2. Run install script
```
./install_obmin.sh
```
3. Restart Gnome to reload extensions by:
 * user's `Log-out/Log-in` (_X11/Wayland_)
 * Alt-F2 `r` command (_X11 only_)
 * or just reboot PC (_X11/Wayland_)
4. Turn on the extension
 * [local extensions page](https://extensions.gnome.org/local/)
 * or `gnome-shell-extension-prefs` tool
 * or in the `gnome-tweak-tool`

**Comment by deikatsuo** [comment]
ok
